# Generated by Django 3.2.20 on 2023-08-22 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imagebase64_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebase64',
            name='id',
            field=models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
