# Generated by Django 3.2.20 on 2023-08-22 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_imagebase64_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebase64',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
